Repository ES2-UFPI/Bando-Contra, pull requests merged in 2021-06, with the labels that each got.

#57 add ModelForm Event #42
  backend/core/admin.py
  backend/core/facade.py
  backend/core/migrations/0003_event.py
  backend/core/migrations/0004_event_partner.py
  backend/core/models.py
Labels: enhancement

#58 add detailSchedule view
  backend/core/migrations/0005_alter_event_options.py
  backend/core/models.py
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/partner/schedule.html
Labels: enhancement

#60 Create ModelForm for issue #43
  backend/core/forms.py
Labels: enhancement

#59 Creating Model Services (#54)
  backend/core/facade.py
  backend/core/models.py
  backend/core/test/__init__.py
  backend/core/test/test_models.py
  backend/core/tests.py
  backend/core/views.py
Labels: enhancement

#61 Add Create View Add Event #44
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/partner/addEvent.html
Labels: enhancement

#62 add Schedule template #50
  backend/core/views.py
  backend/urls.py
  frontend/js/schedule-control.js
  frontend/templates/core/user/partner/schedule.html
Labels: enhancement

#63 Create Register Event Template #45
  backend/core/facade.py
  backend/core/forms.py
  backend/core/models.py
  backend/core/views.py
  frontend/templates/core/user/partner/addEvent.html
Labels: enhancement

#65 Fix Departure/Arrival validation issue
  backend/core/forms.py
  backend/core/migrations/0006_service.py
Labels: bug

#69 Create View Edit Event #36
  backend/core/facade.py
  backend/core/test/test_edit_event.py
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/partner/addEvent.html
  frontend/templates/core/user/partner/schedule.html
Labels: enhancement

#70 Add deleteEvent view #37
  backend/core/facade.py
  backend/core/test/test_delete_event.py
  backend/core/views.py
  backend/urls.py
Labels: enhancement

#71 add delete option to the schedule template #38
  frontend/js/delete_ajax.js
  frontend/templates/core/user/partner/schedule.html
Labels: enhancement

#68 Create template for addService (#47)
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/client/addService.html
Labels: enhancement

#73 put all tests in a single file
  backend/core/test/__init__.py
  backend/core/test/test_delete_event.py
  backend/core/test/test_edit_event.py
  backend/core/test/test_models.py
  backend/core/tests.py
Labels: bug

#74 add deploy and tests workflow
  .github/workflows/dev.yaml
  requirements.txt
Labels: enhancement

#75 Add view editService #48
  backend/core/admin.py
  backend/core/forms.py
  backend/core/views.py
  backend/urls.py
Labels: bug, enhancement

#76 Feature/add view detail service
  backend/core/facade.py
  backend/core/views.py
  backend/urls.py
Labels: enhancement

#77 Feature/add detail service template
  backend/core/models.py
  frontend/templates/core/user/service.html
Labels: enhancement

#78 Add pairEvent method #55
  backend/core/utils.py
  backend/core/views.py
Labels: enhancement
