Repository ES2-UFPI/Bando-Contra, pull requests merged in 2021-07, with the labels that each got.

#100 add listClientServices view
  backend/core/tests.py
  backend/core/utils.py
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/client/listServices.html
Labels: enhancement, help wanted

#101 #83 Create View listServices(Partner)
  backend/core/models.py
  backend/core/tests.py
  backend/core/utils.py
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/partner/listServices.html
Labels: enhancement

#103 add logout #99
  backend/core/tests.py
  backend/urls.py
  frontend/templates/base.html
  frontend/templates/registration/login.html
  settings/settings.py
Labels: enhancement

#102 add list Services template #81
  backend/core/tests.py
  backend/core/utils.py
  frontend/templates/core/user/client/listServices.html
  frontend/templates/core/user/listServices.html
  frontend/templates/core/user/partner/listServices.html
  settings/settings.py
Labels: enhancement

#104 Add Robust validation on creation of events #86
  backend/core/forms.py
  backend/core/models.py
  backend/core/tests.py
  backend/core/utils.py
  backend/core/views.py
Labels: enhancement

#106 Senhas criptografia #(96)
  backend/core/facade.py
  backend/core/forms.py
  backend/core/migrations/0007_auto_20210717_0943.py
  backend/core/models.py
  backend/core/tests.py
Labels: enhancement

#108 add TestAuthentication case #107
  backend/core/tests.py
Labels: bug

#109 add login view #97
  backend/core/tests.py
Labels: enhancement

#105 Add Service Feedback #89
  backend/core/facade.py
  backend/core/forms.py
  backend/core/migrations/0007_auto_20210717_1356.py
  backend/core/models.py
  backend/core/tests.py
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/client/feedback.html
  frontend/templates/core/user/client/listServices.html
  frontend/templates/core/user/listServices.html
  frontend/templates/core/user/partner/listServices.html
Labels: enhancement

#111 Add Partner Info Access Permissions #95
  backend/core/tests.py
  backend/core/views.py
Labels: enhancement

#112 Add Partner Service Access Permissions #93
  backend/core/facade.py
  backend/core/forms.py
  backend/core/migrations/0008_auto_20210717_1609.py
  backend/core/migrations/0009_alter_service_problemdescription.py
  backend/core/migrations/0010_rename_produtcstatus_service_productstatus.py
  backend/core/models.py
  backend/core/tests.py
  backend/core/views.py
  backend/urls.py
  frontend/templates/core/user/partner/editService.html
Labels: enhancement

#113 Add Partner Event Access Permissions #91
  backend/core/tests.py
  backend/core/views.py
Labels: enhancement

#114 permissions Service #92
  backend/core/facade.py
  backend/core/forms.py
  backend/core/migrations/0011_auto_20210717_1826.py
  backend/core/models.py
  backend/core/tests.py
  backend/core/views.py
Labels: enhancement

#120 Fix arrival and departure in schedule page #117
  backend/core/forms.py
  backend/core/tests.py
  backend/core/views.py
  frontend/templates/core/user/partner/schedule.html
Labels: bug

#122 title add all pages #118
  frontend/templates/core/user/client/addService.html
  frontend/templates/core/user/client/feedback.html
  frontend/templates/core/user/client/listServices.html
  frontend/templates/core/user/client/register.html
  frontend/templates/core/user/partner/addEvent.html
  frontend/templates/core/user/partner/editService.html
  frontend/templates/core/user/partner/listServices.html
  frontend/templates/core/user/partner/register.html
  frontend/templates/core/user/service.html
Labels: bug

#123 feature: add login template #98
  frontend/templates/registration/login.html
Labels: enhancement

#124 chore: add tests to client event permissions
  backend/core/tests.py
Labels: chore

#125 feature: add notify status module
  backend/core/views.py
  settings/settings.py
Labels: enhancement

#126 chore: add client info access permissions
  backend/core/tests.py
  backend/core/views.py
Labels: chore

#128 Fix templates bugs
  frontend/templates/core/user/service.html
  frontend/templates/registration/login.html
Labels: bug

#129 fix: fix some bugs in template
  frontend/templates/core/user/service.html
  frontend/templates/registration/login.html
Labels: bug

#130 Fix redirect login
  settings/settings.py
Labels: bug

#131 fix: fix redirect login
  settings/settings.py
Labels: bug
